repos:
  # Rust Clippy for linting
  - repo: https://github.com/rust-lang/rust-clippy
    rev: ''  # Use the latest revision
    hooks:
      - id: clippy

  # Rustfmt for formatting Rust code
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        entry: cargo fmt -- --check
        language: system
        types: [rust]

  # TOML Formatter for formatting TOML files, using taplo-cli
  - repo: https://github.com/tamasfe/taplo
    rev: '0.5.0'  # Specify a version of taplo-cli
    hooks:
      - id: taplo
        name: taplo-format
        entry: taplo format
        args: ["--check"]
        files: \.toml$

  # General house-keeping and merge conflict checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: no-commit-to-branch
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-symlinks
      - id: pretty-format-json
        args: ['--autofix']