debug = true
uid = 0
mount_dir = "./mountdir"
command = "/usr/bin/python3 -m http.server 8000"
additional_paths = [
    "/lib64:/lib64",
    "/lib:/lib",
    "/usr/lib:/usr/lib",
    "/usr/lib64:/usr/lib64",
    "/bin:/bin",
    "/usr/bin:/usr/bin",        # Path for Python3 executable
    "/usr/local/bin:/usr/local/bin",  # Additional binaries
    "/usr/lib/python3.10:/usr/lib/python3.10",  # Python3.10 standard library
    "/usr/local/lib/python3.10/dist-packages:/usr/local/lib/python3.10/dist-packages"  # Python3.10 site-packages
]
