debug = true
uid = 0
mount_dir = "./dvwa_dir"
command = "/usr/sbin/apache2ctl -D FOREGROUND"
additional_paths = [
    "/lib64:/lib64:ro",
    "/lib:/lib:ro",
    "/usr/lib:/usr/lib:ro",
    "/usr/lib64:/usr/lib64:ro",
    "/bin:/bin:ro",
    "/usr/bin:/usr/bin:ro",
    "/usr/local/bin:/usr/local/bin:ro",
    "/usr/lib/php:/usr/lib/php:ro",
    "/etc/apache2:/etc/apache2",
    "/var/www/html:/var/www/html",
    "/var/lib/mysql:/var/lib/mysql",
    "/usr/sbin:/usr/sbin:ro",
    "/var/run:/var/run",
    "/var/lock:/var/lock",
    "/dev:/dev",
    "/tmp:/tmp",
    "/etc/passwd:/etc/passwd:ro",
    "/etc/group:/etc/group:ro"
]
