debug = true
uid = 0
mount_dir = "./juice-shop"
command = "/usr/bin/npm start -- --host 172.18.0.2"

additional_paths = [
    "/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu",
    "/lib:/lib",
    "/lib64:/lib64",
    "/usr/lib:/usr/lib",
    "/usr/lib64:/usr/lib64",
    "/bin:/bin",
    "/usr/bin:/usr/bin",
    "/usr/local/bin:/usr/local/bin", 
    "/usr/local/lib:/usr/local/lib", 
]
