debug = true
uid = 0
mount_dir = "./mountdir/website"
command = "/bin/python3 -m http.server 3000"
additional_paths = [
    "/lib64:/lib64",
    "/lib:/lib",
    "/usr/lib:/usr/lib",
    "/usr/lib64:/usr/lib64",
    "/bin:/bin",
]
