debug = true
uid = 0
mount_dir = "./webgoat_dir"
command = "/usr/lib/jvm/java-17-openjdk-amd64/bin/java -jar webgoat.jar --server.address=172.18.0.2 --server.port=8080"

additional_paths = [
    "/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu",
    "/lib:/lib",
    "/lib64:/lib64",
    "/usr/lib:/usr/lib",
    "/usr/lib64:/usr/lib64",
    "/bin:/bin",
    "/usr/bin:/usr/bin",
    "/usr/lib/jvm/java-17-openjdk-amd64/lib:/usr/lib/jvm/java-17-openjdk-amd64/lib",
    "/usr/lib/jvm/java-17-openjdk-amd64/bin:/usr/lib/jvm/java-17-openjdk-amd64/bin",
    "/usr/lib/jvm/java-17-openjdk-amd64/conf/security:/usr/lib/jvm/java-17-openjdk-amd64/conf/security",
]
